const { Pool } = require('pg');
const crypto = require('crypto');
const assert = require('node:assert/strict');

(async () => {
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const sid = crypto.randomUUID();
  const expire = new Date(Date.now() + 10 * 60 * 1000);
  const sess = { cookie: { originalMaxAge: 600000, expires: expire.toISOString(), secure: true, httpOnly: true, path: '/', sameSite: 'lax' }, user: process.env.ADMIN_USERNAME };
  await pool.query('INSERT INTO app_sessions (sid, sess, expire) VALUES ($1, $2, $3)', [sid, sess, expire]);
  const signature = crypto.createHmac('sha256', process.env.SESSION_SECRET).update(sid).digest('base64').replace(/=+$/, '');
  const headers = { cookie: `abasto_admin=s:${sid}.${signature}`, 'content-type': 'application/json' };
  const label = `smoke-envios-${sid.slice(0, 8)}`;
  const firstQuestion = `${label} hacen envios??`;
  const secondQuestion = `${label} enviozz hacen??`;
  const get = () => fetch('http://127.0.0.1:4002/api/ai', { headers });
  const initial = await get();
  const initialBody = await initial.json();
  const toggleOn = await fetch('http://127.0.0.1:4002/api/ai/status', { method: 'PATCH', headers, body: JSON.stringify({ enabled: true }) });
  const enabledBody = await toggleOn.json();
  const createLabel = await fetch('http://127.0.0.1:4002/api/ai/labels', { method: 'POST', headers, body: JSON.stringify({ name: label, answer: 'smoke ai respuesta guardada\n\n[[MENU]]' }) });
  const labelBody = await createLabel.json();
  const autoTest = await fetch('http://127.0.0.1:4002/api/ai/test', { method: 'POST', headers, body: JSON.stringify({ question: `hacen ${label}??` }) });
  const autoBody = await autoTest.json();
  const createRule = await fetch('http://127.0.0.1:4002/api/ai/answers', { method: 'POST', headers, body: JSON.stringify({ question: firstQuestion, labelId: labelBody.id, answer: 'smoke ai respuesta guardada\n\n[[MENU]]' }) });
  const rule = await createRule.json();
  const second = await fetch('http://127.0.0.1:4002/api/ai/answers', { method: 'POST', headers, body: JSON.stringify({ question: secondQuestion, labelId: labelBody.id, answer: 'smoke ai respuesta guardada\n\n[[MENU]]' }) });
  const secondBody = await second.json();
  const test = await fetch('http://127.0.0.1:4002/api/ai/test', { method: 'POST', headers, body: JSON.stringify({ question: `${label} enviozz hacen??` }) });
  const testBody = await test.json();
  const edited = await fetch('http://127.0.0.1:4002/api/ai/labels/' + labelBody.id, { method: 'PATCH', headers, body: JSON.stringify({ name: label, answer: 'smoke ai respuesta editada\n\n[[MENU]]' }) });
  const editedBody = await edited.json();
  const testEdited = await fetch('http://127.0.0.1:4002/api/ai/test', { method: 'POST', headers, body: JSON.stringify({ question: `${label} enviozz hacen??` }) });
  const testEditedBody = await testEdited.json();
  const toggleOff = await fetch('http://127.0.0.1:4002/api/ai/status', { method: 'PATCH', headers, body: JSON.stringify({ enabled: false }) });
  await toggleOff.json();
  await fetch('http://127.0.0.1:4002/api/ai/labels/' + labelBody.id, { method: 'DELETE', headers });
  if (rule.id) await fetch('http://127.0.0.1:4002/api/ai/answers/' + rule.id, { method: 'DELETE', headers });
  await pool.query('DELETE FROM ai_answer_rules WHERE question LIKE $1 OR intent_label LIKE $1', [`%${label}%`]);
  await pool.query('DELETE FROM ai_query_logs WHERE question LIKE $1', [`%${label}%`]);
  const final = await get();
  const finalBody = await final.json();
  assert.equal(initial.status, 200);
  assert.ok(Array.isArray(initialBody.labels));
  assert.equal(createLabel.status, 201);
  assert.equal(autoTest.status, 200);
  assert.equal(autoBody.answer?.label, label);
  assert.equal(autoBody.answer?.text, 'smoke ai respuesta guardada');
  assert.equal(createRule.status, 201);
  assert.equal(second.status, 201);
  assert.equal(test.status, 200);
  assert.equal(testBody.answer?.label, label);
  assert.equal(testBody.answer?.text, 'smoke ai respuesta guardada');
  assert.equal(testBody.answer?.sendMenuAfter, true);
  assert.equal(testEdited.status, 200);
  assert.equal(testEditedBody.answer?.text, 'smoke ai respuesta editada');
  assert.equal(testEditedBody.answer?.sendMenuAfter, true);
  assert.equal(finalBody.settings?.enabled, false);
  console.log(JSON.stringify({ initialStatus: initial.status, initialEnabled: initialBody.settings?.enabled, toggleOn: enabledBody.enabled, createdLabel: createLabel.status, savedRule: createRule.status, aliasRule: secondBody.label, matchedLabel: testBody.answer?.label, manualAnswer: testBody.answer?.text, editedAnswer: testEditedBody.answer?.text, sendsMenu: testBody.answer?.sendMenuAfter, markerLeaked: String(testBody.answer?.text ?? '').includes('[[MENU]]'), toggleOff: finalBody.settings?.enabled, finalRules: finalBody.rules?.length }));
  await pool.query('DELETE FROM app_sessions WHERE sid = $1', [sid]);
  await pool.end();
})().catch(error => { console.error(error.message); process.exit(1); });
